# Generated by Django 4.0.5 on 2022-06-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecurityApp', '0003_certification_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='scanVul',
        ),
    ]
