# Generated by Django 4.0.5 on 2022-06-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecurityApp', '0006_alter_certification_image_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan_vul',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scan_vul',
            name='titleVul',
        ),
        migrations.AddField(
            model_name='scan_vul',
            name='ScannerName',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan_vul',
            name='VulnerabilityName',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan_vul',
            name='stateOFvulnerabitlity',
            field=models.CharField(choices=[('active', 'active'), ('Non Active', 'Non Active')], default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan_vul',
            name='type_OS',
            field=models.CharField(choices=[('Microsoft OS', 'Microsoft OS'), ('MAC OS', 'MAC OS'), ('Linux OS', 'Linux OS'), ('Unix OS', 'Unix OS')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
