# Generated by Django 4.0.5 on 2022-06-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecurityApp', '0007_remove_scan_vul_name_remove_scan_vul_titlevul_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan_vul',
            old_name='stateOFvulnerabitlity',
            new_name='stateOFvul',
        ),
    ]
