# Generated by Django 4.0.5 on 2022-06-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecurityApp', '0008_rename_stateofvulnerabitlity_scan_vul_stateofvul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_vul',
            name='type_OS',
            field=models.CharField(choices=[('Microsoft OS', 'Microsoft OS'), ('MAC OS', 'MAC OS'), ('Linux OS', 'Linux OS'), ('Unix OS', 'Unix OS'), ('Other', 'Other')], max_length=250),
        ),
    ]
